from qcinput.config import QCInputConfig


def render_gaussian_input(
    *,
    xyz_text: str,
    config: QCInputConfig,
    source_xyz_name: str,
) -> str:
    if config.nprocshared is None or config.mem is None or config.method_basis is None:
        raise ValueError("Gaussian config is incomplete.")
    route = " ".join((config.method_basis, *config.task_keywords))
    lines = [
        f"%NProcShared={config.nprocshared}",
        f"%Mem={config.mem}",
        f"#P {route}",
        "",
        f"Generated by qcinput from {source_xyz_name}",
        "",
        f"{config.charge} {config.multiplicity}",
        xyz_text,
        "",
        "",
        "",
    ]
    return "\n".join(lines)
