from qcinput.config import QCInputConfig


def render_orca_input(
    *,
    xyz_text: str,
    config: QCInputConfig,
    source_xyz_name: str,
) -> str:
    if config.nprocs is None or config.maxcore is None:
        raise ValueError("ORCA config is incomplete.")
    keywords = " ".join((*config.task_keywords, *config.base_keywords))
    lines = [
        f"# Generated by qcinput from {source_xyz_name}",
        f"! {keywords}",
        f"%pal nprocs {config.nprocs} end",
        f"%maxcore {config.maxcore}",
        f"* xyz {config.charge} {config.multiplicity}",
        xyz_text,
        "*",
        "",
    ]
    return "\n".join(lines)
